services:
  be-lemdiklat-permapendis:
    image: be-lemdiklat-permapendis
    build:
      context: .
      dockerfile: be-lemdiklat-permapendis/Dockerfile
    ports:
      - "5001:5001"
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=lemdiklat_permapendis;Username=postgres;Password=postgres
      - Cors__AllowedOrigins__0=http://localhost:3000
      - Cors__AllowedOrigins__1=http://localhost:5173
      - Cors__AllowedOrigins__2=http://localhost:8080
      - Cookie__Name=auth
      - Cookie__ExpireDays=3
      - Cookie__SlidingExpiration=true
      - Cookie__HttpOnly=true
      - Cookie__Secure=false
      - Cookie__SameSite=Lax
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5001

